=== bidon-io/bidon_backend/internal/sdkapi/v2/openapi/schemas/auction-response.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "auction-response.schema.json",
  "title": "AuctionResponse",
  "type": "object",
  "properties": {
    "auction_configuration_id": {
      "type": "integer",
      "format": "int64",
      "description": "ID of the auction configuration"
    },
    "auction_configuration_uid": {
      "type": "string",
      "description": "UID of the auction configuration"
    },
    "external_win_notifications": {
      "type": "boolean",
      "description": "Indicates if external win notifications are enabled"
    },
    "ad_units": {
      "type": "array",
      "description": "List of ad units returned in the auction",
      "items": {
        "$ref": "ad-unit.schema.json"
      }
    },
    "no_bids": {
      "type": "array",
      "description": "List of ad units that received no bids",
      "items": {
        "$ref": "ad-unit.schema.json"
      }
    },
    "segment": {
      "$ref": "segment.schema.json",
      "description": "Segment information related to the auction"
    },
    "token": {
      "type": "string",
      "description": "Token"
    },
    "auction_pricefloor": {
      "type": "number",
      "description": "PriceFloor for the auction",
      "minimum": 0
    },
    "auction_timeout": {
      "type": "integer",
      "description": "Timeout for the auction in milliseconds"
    },
    "auction_id": {
      "type": "string",
      "description": "Unique identifier for the auction"
    }
  },
  "required": [
    "auction_configuration_id",
    "auction_configuration_uid",
    "external_win_notifications",
    "ad_units",
    "segment",
    "token",
    "auction_pricefloor",
    "auction_timeout",
    "auction_id"
  ],
  "additionalProperties": false
}

=== bidon-io/bidon_backend/internal/sdkapi/v2/apihandlers/testdata/auction/valid_response_coppa.json
{
  "auction_configuration_id": 1,
  "auction_configuration_uid": "1701972528521547776",
  "external_win_notifications": false,
  "ad_units": [
    {
      "bid_type": "RTB",
      "demand_id": "mobilefuse",
      "label": "mobilefuse",
      "pricefloor": 0.7,
      "uid": "123_mobilefuse",
      "timeout": 6000,
      "ext": {
        "signaldata": "signal_data",
        "placement_id": "123"
      }
    },
    {
      "demand_id": "meta",
      "uid": "123_meta",
      "label": "meta",
      "pricefloor": 0.6,
      "bid_type": "RTB",
      "timeout": 6000,
      "ext": {
        "payload": "payload",
        "placement_id": "123"
      }
    },
    {
      "bid_type": "RTB",
      "demand_id": "amazon",
      "label": "amazon",
      "pricefloor": 0.5,
      "uid": "123_amazon",
      "timeout": 6000,
      "ext": {
        "slot_uuid": "uuid1"
      }
    }
  ],
  "no_bids": [
    {
      "bid_type": "RTB",
      "demand_id": "vungle",
      "label": "vungle",
      "pricefloor": 0,
      "uid": "123_vungle",
      "timeout": 6000,
      "ext": {
        "placement_id": "123"
      }
    }
  ],
  "segment": {
    "id": "1",
    "uid": "1701972528521547776"
  },
  "token": "{}",
  "auction_pricefloor": 0.001,
  "auction_timeout": 30000,
  "auction_id": "1d7fa438-cd08-4849-80ed-e20d5657a5ea"
}
